---
title: "<span class='letter-cap'>R</span><span class = 'fancy'>esearch</span>"
format: html
include-in-header:
    text: |
      <style>
        h2, h3 {
          color: #6a6a00;
        }
        a {
        color: #6a6a00;
        }
        .title {
        color: #6a6a00;
        font-weight: bold;
        }
        .sidebar nav[role="doc-toc"] ul > li > a {
        color: #6a6a00 !important; 
        }
        .toc-color {
        color: #6a6a00;
        }
        #TOC a.active {
        color: #6a6a00 !important;
        font-weight: demi-bold;
        }
      </style>
toc: true
callout-icon: false
---

### [D]{.letter-cap}issertation 

#### Catastrophic Politics: The International Community's Role in Preventing and Responding to Man-Made Disasters

::: {style="font-size: 0.9em;"}
Since 2000, over 16,000 disasters have occurred around the world. Of these disasters, approximately one in every three disasters is of man-made origin. However, studies of man-made disasters make up a very small part of the disaster politics literature with studies mostly using case studies. In my dissertation, I plan to create a novel dataset of technological disasters that will allow me to merge the technical data of disasters with political data. Using this dataset, I then introduce a variety of methods – case studies, experimental surveys, and large-N models – in my endeavor to answer the question of when, how and why does the international community intervene when a technological disaster strikes a country.

[*For detailed summaries of the different sections and chapters of my dissertation please see below.]{style="font-size: 0.8em; line-height: 0.8;"}
:::

:::: {.callout-note collapse="true" icon="false"}
## Section I: Disaster Occurrence as a Failure of Prevention

::: {style="font-size: 0.9em;"}
This first section, discusses disaster occurrence on two levels: international and domestic. International organizations vary in their evolution and governance structures which, in turn, affects their ability to prevent disasters in their respective fields. Using case studies, I develop a theory of effective governance in preventing man-made hazards from becoming technological disasters by comparing the international governance structures of three transportation industries.To study disaster occurrence at the domestic level, I use a selection model to examine how structural and institutional factors within countries affect disaster occurrence and severity.
:::

###### Chapters:

```{=html}
<details style="font-size: 0.9em;">
<summary style = "opacity: 1; color: #6a6a00; text-decoration: underline;">Global Disaster Governance: A Comparison of the Transportation Industries Prevention Strategies</summary>

<b>Abstract: </b>What are the regimes in place for preventing disasters at the supranational level? This chapter discusses the international legal framework or lack thereof that governs disaster response. While there is not formal international body for coordinating and governing the prevention of technological disasters, many industries have international organizations that serve this purpose. These organizations have a great deal of variability in how they are designed, level of adoption, and enforceability. This chapter compares the organizational structures of three transportation industries – aviation, rail, and maritime – to understand how these differences prevent and respond to disasters and the observable implications of this with available disaster data. 
</details>
<details style="font-size: 0.9em;">
<summary style = "opacity: 1; color: #6a6a00; text-decoration: underline;">Built for Disaster? Examining Structural Factors Within Countries that Can Increase the Likelihood of or Exacerbate a Disaster Occurrence </summary>

<b>Abstract: </b>Many existing studies of technological disasters have examined them as individual events. However, according to the EM-DAT dataset that tracks and logs disaster occurrences, almost 6000 technological disasters have occurred around the world since the year 2000. Unlike their natural counterparts, these types of disasters are markedly different as political phenomenon. While political choices can make natural disasters worse, their cause is ultimately a function of natural processes. Technological disasters, on the other hand, may have root causes that stem from political or public policy factors. This study will look at governance systems, institutional factors, and other country-level characteristics’ effects on the occurrence, severity, and impact of technological disasters in a country. This project aims to be one of the first that looks at structural and institutional factors - such as level of development, government structure, etc. - within countries that might contribute to the occurrence of technological disasters.
</details>
```
::::

:::: {.callout-note collapse="true" icon="false"}
## Section II: Responses from Other Countries

::: {style="font-size: 0.8em;"}
To study the response of other countries, I use an experimental survey to examine the support for foreign aid from donor publics. Using two randomized surveys, I vary the relationship between the disaster affected country and the United States, the type of technological disaster, and the entity most to blame for the disaster's occurrence. I also look at the observed responses of countries to disasters occuring in other countries. Using a large-N network analytical model, I explore how the relationships between countries impacts their responses in these disaster situations and how the response of one country to a disaster can influence the responses from other countries.
:::

###### Chapters:

```{=html}
<details style="font-size: 0.9em;">
<summary style = "opacity: 1; color: #6a6a00; text-decoration: underline;"> Humanitarianism or Strategic Benefits? Donor Publics’ Support for Foreign Disaster Aid and Blame Attribution for Technological Disasters </summary>


<p class = "vspacer"><b>Abstract: </b>Previous studies of domestic support for foreign aid have explored the various reasons that individuals support or do not support foreign aid. In this study, I examine disaster-related foreign aid specifically to determine whether the nature of disaster situations will affect individuals support for foreign disaster aid. Using a randomized survey experiment, I explore the impact of the relationship between an affected country and a donor country - whether these countries are allies or adversaries - and what type of disaster the affected country is facing - natural or technological. In a pilot study using a sample of UCDavis undergraduate political science students, I find broad support for the assertion that disasters in allies generate more support for disaster aid while the type of disaster appears to be an insignificant determinant of opinions on foreign disaster aid. Subsequent studies are planned to determine how blame attribution for disasters may also play a role in this process and to use samples from beyond the university. This study broadens our understanding of how individuals determine who deserves foreign aid relief when disasters strike. It also starts to compare the two broad categories of disasters in a systematic way to explore how natural and man-made disasters might be different as political phenomenon.</p>
</details>
<details style="font-size: 0.9em;">
<summary style = "opacity: 1; color: #6a6a00; text-decoration: underline;">Phone a Friend: Evaluating the Responses of Other Countries to a Disaster-Affected Country </summary>

<b>Abstract: </b>How do states respond when others are facing technological disasters? While the crisis collaboration has tried to answer this question in relation to other types of political crises, I seek to expand these ideas into the realm of technological disasters. This paper focuses on examining the effect of international relationships between countries in three key ways using network analysis and spatial modeling methods. First, I look at how the relationships between responding countries and affected countries influences whether – and what kind of – a response occurs in an affected country. Second, I examine how the relationships between responding countries and multinational corporations responsible for disasters abroad affects their response. Lastly, I look at diffusion effects of one country’s response on other responding countries. 
</details>
```
::::

:::: {.callout-note collapse="true" icon="false"}
## Section III: Recovery and Political Consequences in Recipient Countries

::: {style="font-size: 0.9em;"}
In the last section, I look at how the disaster occurrence, severity and international response influences domestic politics within affected countries. Specifically, I focus on incumbent survival and approval. I try to understand and unpack how civilians respond to the work of their government and whether a disaster and its origins can create more discontent or a rally around the incumbent effect.
:::

###### Chapters:

```{=html}
<details style="font-size: 0.9em;">
<summary style = "opacity: 1; color: #6a6a00; text-decoration: underline;">Is Help Actually Helpful?: The Effects of Technological Disasters and International Aid on Incumbent Survival and Protest Activity in Recipient Countries</summary>

<b>Abstract: </b>Many studies have looked at the effects of natural disasters on the political systems of the countries in which they occur. These studies have shown that in some cases, there is a rallying effect around incumbents while others have demonstrated an increase in political protest and disapproval for the incumbents. In this study, I use a large-N survival model to examine this question in relation to technological disasters specifically. I hope to examine whether these expectations about citizen’s behavior hold when considering the added effect of culpability in technological disasters to the mix. Furthermore, I examine what factors may lead to a rallying effect versus growing discontent in these countries by looking at the effects of disasters on protest activity, executive approval, election returns, and incumbent survival. 
</details>
```
::::

[Stay tuned...Details and initial visualizations for the disaster dataset are forthcoming!]{style="font-size: 0.9em;"}

### [P]{.letter-cap}eer-[R]{.letter-cap}eviewed [P]{.letter-cap}ublications 

```{=html}
<details>
<summary style = "opacity: 1; color: #212529;">Kinne, Brandon, Juan Tellez, Anya Stewart, Iliyan Iliev, Brandon Derr, <span style="font-weight: bold; color: #6a6a00; ">Shreya Murthy</span>, and Patrick Bernhard. 2026. “Interstate Competition and Transnational Threats: How Networks of Nonstate Actors Increase Conflict between States” <span style = "font-style: italic;">Forthcoming, International Organization.</span></summary>
</details>
```

<!-- <span style = "font-size: 0.9em;"> -->

<!-- <p class="vspacer" style = "line-height: 1.1;"> -->

<!-- <b>Abstract: </b>Scholars and policymakers alike now view competition between states as the primary threat to international security. Yet, the nontraditional threats that previously defined the global security landscape, such as terrorism and civil war, continue to flourish. Recent interstate conflicts have featured nonstate armed groups as central actors, and governments rely on these groups to extend their interests. This paper examines how government support for foreign nonstate actors affects interstate competition. We conceptualize state-nonstate ties as transnational networks comprised of cooperative relationships between governments and foreign terrorist organizations, rebel groups, militias, and civilian groups. We argue that these transnational networks exacerbate interstate tensions in two ways. First, they increase a state's capacity relative to adversaries, which emboldens the government, increases its bargaining leverage, and leads to increased aggression toward other states. Second, they increase a government's liability for the actions of sponsored groups, which leads to unintended confrontations and retaliatory actions by affected targets. To measure interstate competition, we use high-resolution event data on verbal and material conflict between governments. We incorporate these data into network models that allow transnational ties and interstate conflict to co-evolve, such that states form ties to nonstate actors in response to interstate conflict, and those ties in turn influence conflict probability. We find that both the size and structure of governments' respective transnational networks are associated with an increase in verbal and material conflict. Further, this association is particularly strong for states that lack conventional military strength. These findings suggest that cooperation between governments and nonstate actors is integrally connected to interstate competition. -->

<!-- </p> -->

<!-- </span> -->

### [W]{.letter-cap}orking [P]{.letter-cap}apers

Built for Disaster? Examining Structural Factors Within Countries that Can Increase the Likelihood of or Exacerbate a Disaster Occurrence

Humanitarianism or Strategic Benefits? Donor Publics’ Support for Foreign Disaster Aid and Blame Attribution for Technological Disasters

### [G]{.letter-cap}rants and [C]{.letter-cap}onferences

#### Grants

-   University of California, Davis Dean's Summer Graduate Support Award, \$6,000 - May 2025
-   2025 Political Science Summer Methods Travel Support Award, \$1,795 - May 2025
-   Alan Templeton Dissertation Improvement Award, \$2,000 - May 2025
-   2025 Political Science Living Expense Fellowship, \$3,000 - May 2025
-   2024 Political Science Living Expense Fellowship, \$5,000 - May 2024
-   Faculty-Student Summer Research Collaborative Grant, \$5,000 - May 2023
    -   With Gabriella Montinola

#### Conferences

International Studies Association: 2026

Midwestern Political Science Association: 2024, 2025
